import {getOpenReports,getPendingGroups,getOpenIssues} from "./moderation.js";
import './theme.js';import {db} from './firebase.js';import {subscribeAuth,requireAuth,hasRole} from './auth.js';import {collection,getDocs,getCountFromServer,query,orderBy,limit,where,updateDoc,doc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import {getFunctions,httpsCallable} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-functions.js';import { $, escapeHtml, formatDateTime, toast, showModal, initials } from './utils.js';
let adminProfile;
async function count(name,q){if(!db)return '—';try{return (await getCountFromServer(q||collection(db,name))).data().count}catch{return '—'}}
async function loadStats(){for(const n of ['users','posts','groups','issues','reports','events']){$(`[data-stat="${n}"]`).textContent=await count(n)}}
async function loadReports(){if(!db)return;try{const snap=await getDocs(query(collection(db,'reports'),orderBy('createdAt','desc'),limit(15)));const rows=snap.docs.map(d=>({id:d.id,...d.data()}));$('[data-report-rows]').innerHTML=rows.length?rows.map(r=>`<tr><td>${escapeHtml(r.type)}</td><td>${escapeHtml(r.reason)}</td><td><span class="badge ${r.status==='resolved'?'success':'warning'}">${escapeHtml(r.status||'pending')}</span></td><td>${formatDateTime(r.createdAt)}</td><td><button class="btn sm" data-review-report="${r.id}">Review</button></td></tr>`).join(''):'<tr><td colspan="5" class="muted">No reports in the queue.</td></tr>'}catch(e){toast('Could not load moderation queue.','error')}}
async function loadGroups(){if(!db)return;try{const snap=await getDocs(query(collection(db,'groups'),where('status','==','pending'),orderBy('createdAt','desc'),limit(15)));const box=$('[data-pending-groups]');box.innerHTML=snap.docs.length?snap.docs.map(d=>{const g=d.data();return `<div class="moderation-item"><div><strong>${escapeHtml(g.name)}</strong><div class="small muted">${escapeHtml(g.category||'Community')} · ${formatDateTime(g.createdAt)}</div><p class="small muted">${escapeHtml(g.description||'')}</p></div><div class="toolbar"><button class="btn sm primary" data-approve-group="${d.id}">Approve</button><button class="btn sm" data-reject-group="${d.id}">Reject</button></div></div>`}).join(''):'<div class="empty"><i data-lucide="inbox"></i><h3>Nothing awaiting approval</h3></div>'}catch(e){toast('Could not load group approvals.','error')}}
async function loadIssues(){if(!db)return;try{const snap=await getDocs(query(collection(db,'issues'),orderBy('createdAt','desc'),limit(12)));$('[data-admin-issues]').innerHTML=snap.docs.map(d=>{const i=d.data();return `<div class="moderation-item"><div><div class="badge primary">Anonymous Student</div><strong>${escapeHtml(i.title)}</strong><div class="small muted">${escapeHtml(i.category||'Other')} · ${escapeHtml(i.severity||'Medium')}</div></div><button class="btn sm" data-admin-issue="${d.id}">Update</button></div>`}).join('')||'<div class="empty">No issues found.</div>'}catch(e){toast('Could not load issues.','error')}}
async function reviewReport(id){showModal('Review report','<form class="form" id="reportReview"><div class="field"><label>Decision</label><select name="status"><option value="reviewed">Reviewed</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select></div><div class="field"><label>Internal note</label><textarea name="note" maxlength="500"></textarea></div><div style="text-align:right"><button class="btn primary">Save review</button></div></form>');$('#reportReview').addEventListener('submit',async e=>{e.preventDefault();try{const fd=new FormData(e.currentTarget);await httpsCallable(getFunctions(), 'reviewReport')({reportId:id,status:fd.get('status'),note:String(fd.get('note')||'')});document.querySelector('.modal-backdrop')?.remove();toast('Report reviewed');loadReports()}catch(err){toast(err.message,'error')}})}
async function loadGroupRequests(){if(!db)return;try{const snap=await getDocs(query(collection(db,'groupRequests'),where('status','==','pending'),orderBy('createdAt','desc'),limit(15)));const box=$('[data-group-requests]');box.innerHTML=snap.docs.length?snap.docs.map(d=>{const r=d.data();return `<div class="moderation-item"><div><strong>${escapeHtml(r.groupName||r.groupId)}</strong><div class="small muted">Student request · ${formatDateTime(r.createdAt)}</div></div><div class="toolbar"><button class="btn sm primary" data-approve-request="${d.id}">Approve</button><button class="btn sm" data-reject-request="${d.id}">Reject</button></div></div>`}).join(''):'<div class="empty"><h3>No pending requests</h3></div>'}catch(e){toast('Could not load membership requests.','error')}}
async function updateIssue(id){showModal('Update issue status','<form class="form" id="issueReview"><div class="field"><label>Status</label><select name="status"><option>Open</option><option>Under Review</option><option>In Progress</option><option>Resolved</option><option>Closed</option></select></div><div class="field"><label>Public response</label><textarea name="response" maxlength="1000" placeholder="What should students know?"></textarea></div><div style="text-align:right"><button class="btn primary">Update issue</button></div></form>');$('#issueReview').addEventListener('submit',async e=>{e.preventDefault();try{const fd=new FormData(e.currentTarget);await updateDoc(doc(db,'issues',id),{status:fd.get('status'),adminResponse:String(fd.get('response')||''),updatedAt:serverTimestamp()});document.querySelector('.modal-backdrop')?.remove();toast('Issue updated');loadIssues()}catch(err){toast(err.message,'error')}})}
document.addEventListener('click',async e=>{const r=e.target.closest('[data-review-report]');if(r)reviewReport(r.dataset.reviewReport);const a=e.target.closest('[data-approve-group]');if(a){try{await updateDoc(doc(db,'groups',a.dataset.approveGroup),{status:'approved',approvedBy:adminProfile.uid,approvedAt:serverTimestamp()});toast('Group approved');loadGroups();loadStats()}catch(err){toast(err.message,'error')}}const reject=e.target.closest('[data-reject-group]');if(reject){showModal('Reject group','<form id="rejectForm" class="form"><div class="field"><label>Reason</label><textarea name="reason" required maxlength="500"></textarea></div><button class="btn danger">Reject group</button></form>');$('#rejectForm').addEventListener('submit',async ev=>{ev.preventDefault();const fd=new FormData(ev.currentTarget);try{await updateDoc(doc(db,'groups',reject.dataset.rejectGroup),{status:'rejected',rejectionReason:String(fd.get('reason')),reviewedBy:adminProfile.uid,reviewedAt:serverTimestamp()});document.querySelector('.modal-backdrop')?.remove();toast('Group rejected');loadGroups()}catch(err){toast(err.message,'error')}})}const ar=e.target.closest('[data-approve-request]');if(ar){try{await httpsCallable(getFunctions(),'reviewGroupRequest')({requestId:ar.dataset.approveRequest,decision:'approved'});toast('Request approved');loadGroupRequests()}catch(err){toast(err.message,'error')}}const rr=e.target.closest('[data-reject-request]');if(rr){try{await httpsCallable(getFunctions(),'reviewGroupRequest')({requestId:rr.dataset.rejectRequest,decision:'rejected'});toast('Request rejected');loadGroupRequests()}catch(err){toast(err.message,'error')}}const issue=e.target.closest('[data-admin-issue]');if(issue)updateIssue(issue.dataset.adminIssue)});
subscribeAuth((u,p)=>{if(!requireAuth())return;if(!hasRole('platformAdmin','moderator')){location.href='home.html';return}adminProfile=p;loadStats();loadReports();loadGroups();loadGroupRequests();loadIssues()});

export async function loadModerationQueues(){
 const [reports,groups,issues]=await Promise.all([getOpenReports(),getPendingGroups(),getOpenIssues()]);
 return {reports,groups,issues};
}
