import {toggleEventInterest} from "./interactions.js";
import {isEventInterested} from "./data-layer.js";
import './theme.js';import {db} from './firebase.js';import {subscribeAuth,requireAuth} from './auth.js';import {collection,getDocs,query,orderBy,limit} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';import { $, escapeHtml, formatDateTime, toast } from './utils.js';
const demo=[{title:'Campus Hacknight',description:'Build something useful with peers.',venue:'Main Lab',date:new Date('2026-09-18T17:30:00'),organizer:'Coding Community',interestedCount:72},{title:'Freshers Connect',description:'Meet people, clubs and campus communities.',venue:'Auditorium',date:new Date('2026-09-23T16:00:00'),organizer:'Campus Connect',interestedCount:140},{title:'Design Meetup',description:'UI, product thinking and portfolio feedback.',venue:'Innovation Lab',date:new Date('2026-10-02T15:00:00'),organizer:'Design Club',interestedCount:38}];
function card(e){const d=e.date?.toDate?e.date.toDate():new Date(e.date);return `<article class="card event-card event-enhanced"><div class="event-date-large"><span>${d.toLocaleString(undefined,{month:'short'}).toUpperCase()}</span><strong>${d.getDate()}</strong></div><div class="event-main"><div class="badge primary">${escapeHtml(e.organizer||'Campus event')}</div><h3>${escapeHtml(e.title)}</h3><p class="muted">${escapeHtml(e.description||'')}</p><div class="small muted row"><i data-lucide="clock"></i>${formatDateTime(e.date)} <span>•</span><i data-lucide="map-pin"></i>${escapeHtml(e.venue||'Campus')}</div></div><div class="event-action"><button class="btn sm primary" data-interest>Interested · ${e.interestedCount||0}</button></div></article>}
async function load(){let items=[];if(db){try{const snap=await getDocs(query(collection(db,'events'),orderBy('date','asc'),limit(30)));items=snap.docs.map(d=>({id:d.id,...d.data()}))}catch(e){toast('Could not load events.','error')}}if(!items.length)items=demo;$('#eventList').innerHTML=items.map(card).join('');window.lucide?.createIcons()}
document.addEventListener('click',e=>{if(e.target.closest('[data-interest]')){const b=e.target.closest('[data-interest]');if(!db)return toast('Connect Firebase to save event interest.','warning');b.classList.toggle('active');b.textContent=b.classList.contains('active')?'Interested':'Interested'}});subscribeAuth((u,p)=>{if(!requireAuth())return;load()});

export async function refreshEventInterestButton(eventId,button){
 try{button.classList.toggle("active",await isEventInterested(eventId));}catch(e){}
}
