import './theme.js';
import {db} from './firebase.js';
import {subscribeAuth,requireAuth,currentProfile,currentUser} from './auth.js';
import {collection,getDocs,query,where,limit,addDoc,serverTimestamp,doc,getDoc} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { $, $$, escapeHtml, initials, toast, showModal } from './utils.js';
import {requestMembership} from './services.js';
let all=[];
function card(g){return `<article class="card group-card group-card-enhanced" data-group data-name="${escapeHtml((g.name||'').toLowerCase())}" data-category="${escapeHtml(g.category||'')}" style="padding:0"><div class="group-cover"><div class="cover-label"><span class="badge">${escapeHtml(g.category||'Community')}</span></div></div><div class="group-body"><div class="group-avatar">${g.imageURL?`<img src="${escapeHtml(g.imageURL)}" alt="">`:initials(g.name)}</div><div class="split" style="align-items:flex-start;margin-top:10px"><div><h3 style="margin:0">${escapeHtml(g.name)}</h3><div class="small muted">${Number(g.memberCount||0)} members</div></div><span class="badge success">${escapeHtml(g.status||'approved')}</span></div><p class="muted small">${escapeHtml(g.description||'A community on Campus Connect.')}</p><div class="toolbar"><a class="btn sm" href="group.html?id=${encodeURIComponent(g.id||'demo')}"><i data-lucide="arrow-up-right"></i>Open</a><button class="btn sm primary" data-join-group="${escapeHtml(g.id||'')}"><i data-lucide="user-plus"></i>Join</button></div></div></article>`}
async function load(){all=[];if(db){try{const snap=await getDocs(query(collection(db,'groups'),where('status','==','approved'),limit(50)));all=snap.docs.map(d=>({id:d.id,...d.data()}))}catch(e){toast('Could not load communities.','error')}}if(!all.length)all=[{id:'coding',name:'Campus Coders',category:'Coding',memberCount:184,description:'Projects, interview prep, hackathons and peer learning.',status:'approved'},{id:'placement',name:'Placement Prep',category:'Placement',memberCount:312,description:'A focused place for aptitude, DSA, resumes and interview discussions.',status:'approved'},{id:'music',name:'Music Society',category:'Music',memberCount:96,description:'For singers, musicians and performers.',status:'approved'}];render(all)}
function render(items){const box=$('[data-groups]');box.innerHTML=items.map(card).join('');const countEl=$('[data-group-count]'); if(countEl) countEl.textContent=`${items.length} communities`;window.lucide?.createIcons()}
function filter(){const term=($('#groupSearch')?.value||'').toLowerCase().trim();const cat=$('.chip.active')?.dataset.category||'All';render(all.filter(g=>(!term||(g.name||'').toLowerCase().includes(term)||(g.description||'').toLowerCase().includes(term))&&(cat==='All'||g.category===cat)))}
function createGroup(){showModal('Create a group','<form class="form" id="groupForm"><div class="field"><label>Group name</label><input required name="name" maxlength="80" placeholder="e.g. Campus Developers"></div><div class="field"><label>Description</label><textarea required name="description" maxlength="500" placeholder="What is this community for?"></textarea></div><div class="grid grid-2"><div class="field"><label>Category</label><select name="category"><option>Coding</option><option>Placement</option><option>Study</option><option>Music</option><option>Sports</option><option>Gaming</option><option>Photography</option><option>Entrepreneurship</option><option>Clubs</option><option>Department</option></select></div><div class="field"><label>Privacy</label><select name="privacy"><option value="public">Public</option><option value="approval">Request to join</option></select></div></div><div class="field"><label>Community rules</label><textarea name="rules" maxlength="800" placeholder="Be respectful, stay on topic..."></textarea></div><div class="notice small">New groups are submitted for platform review before public discovery.</div><div style="text-align:right"><button class="btn primary"><i data-lucide="send"></i>Submit for approval</button></div></form>');window.lucide?.createIcons();$('#groupForm').addEventListener('submit',async e=>{e.preventDefault();if(!db)return toast('Connect Firebase to create a group.','warning');const fd=new FormData(e.currentTarget);try{await addDoc(collection(db,'groups'),{name:String(fd.get('name')).trim(),description:String(fd.get('description')).trim(),category:fd.get('category'),privacy:fd.get('privacy'),rules:String(fd.get('rules')||'').trim(),createdBy:currentUser.uid,memberCount:1,status:'pending',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});toast('Group submitted for approval');document.querySelector('.modal-backdrop')?.remove()}catch(err){toast(err.message,'error')}})}
document.addEventListener('input',e=>{if(e.target.id==='groupSearch')filter()});document.addEventListener('click',async e=>{const chip=e.target.closest('[data-category]');if(chip){$$('[data-category]').forEach(x=>x.classList.remove('active'));chip.classList.add('active');filter()}if(e.target.closest('[data-create-group]'))createGroup();const btn=e.target.closest('[data-join-group]');if(btn){const id=btn.dataset.joinGroup;if(!id||id==='demo')return toast('Demo group shown for exploration.','warning');try{await requestMembership(id,currentUser.uid);btn.disabled=true;btn.textContent='Requested';toast('Membership request sent')}catch(err){toast(err.message,'error')}}});subscribeAuth((u,p)=>{if(!requireAuth())return;load()});
