import {isGroupMember,hasGroupRequest} from "./data-layer.js";
import './theme.js';import {db} from './firebase.js';import {subscribeAuth,requireAuth,currentProfile,currentUser} from './auth.js';import {doc,getDoc,collection,getDocs,query,where,limit,addDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';import { $, getQuery, escapeHtml, initials, toast } from './utils.js';
const demo={id:'demo',name:'Campus Coders',category:'Coding',description:'Projects, interview prep, hackathons and peer learning.',memberCount:184,status:'approved',rules:'Be useful, respectful and on-topic.'};let group=demo;
async function load(){const id=getQuery('id');if(db&&id){try{const s=await getDoc(doc(db,'groups',id));if(s.exists())group={id:s.id,...s.data()}}catch(e){toast('Could not load this group.','error')}}document.querySelector('[data-group-name]').textContent=group.name;document.querySelector('[data-group-category]').textContent=group.category||'Community';document.querySelector('[data-group-description]').textContent=group.description||'';document.querySelector('[data-member-count]').textContent=`${group.memberCount||0} members`;document.querySelector('[data-group-avatar]').textContent=initials(group.name);document.querySelector('[data-group-rules]').textContent=group.rules||demo.rules;loadGroupPosts();loadMembers()}
async function loadGroupPosts(){let posts=[];if(db&&group.id!=='demo'){try{const snap=await getDocs(query(collection(db,'posts'),where('groupId','==',group.id),limit(15)));posts=snap.docs.map(d=>({id:d.id,...d.data()}))}catch{}}if(!posts.length)posts=[{authorName:'Campus Connect',branch:'Community',text:'This is the start of the group conversation. Share projects, questions, opportunities and useful resources.',likes:12,comments:4,createdAt:new Date()}];document.querySelector('[data-group-posts]').innerHTML=posts.map(p=>`<article class="card post-card"><div class="post-head"><div class="avatar">${initials(p.authorName)}</div><div class="post-meta"><strong>${escapeHtml(p.authorName)}</strong><span>${escapeHtml(p.branch||'Student')} · ${p.createdAt?.toDate?p.createdAt.toDate().toLocaleString(): 'Just now'}</span></div></div><div class="post-text">${escapeHtml(p.text)}</div><div class="post-actions"><button class="action"><i data-lucide="heart"></i>${p.likes||0}</button><button class="action"><i data-lucide="message-circle"></i>${p.comments||0}</button></div></article>`).join('');window.lucide?.createIcons()}
async function loadMembers(){const box=document.querySelector('[data-members]');if(!box)return;if(!db||group.id==='demo'){box.innerHTML='<div class="empty"><i data-lucide="users"></i><h3>184 members</h3><p>Members appear here once the community is connected to Firebase.</p></div>';window.lucide?.createIcons();return}try{const snap=await getDocs(query(collection(db,'groupMembers'),where('groupId','==',group.id),limit(20)));box.innerHTML=snap.docs.map(d=>`<div class="list-row row"><div class="avatar">${initials(d.data().displayName||'Student')}</div><div><strong>${escapeHtml(d.data().displayName||'Student')}</strong><div class="small muted">${escapeHtml(d.data().role||'Member')}</div></div></div>`).join('')||'<div class="empty"><h3>No members listed yet</h3></div>'}catch{box.innerHTML='<div class="empty"><h3>Members unavailable</h3></div>'}}
document.addEventListener('click',async e=>{if(e.target.closest('[data-group-join]')){if(!db||group.id==='demo')return toast('Connect Firebase to persist membership.','warning');try{await addDoc(collection(db,'groupRequests'),{groupId:group.id,userId:currentUser.uid,status:'pending',createdAt:serverTimestamp()});toast('Membership request sent')}catch(err){toast(err.message,'error')}}if(e.target.closest('[data-group-post]')){if(!db||group.id==='demo')return toast('Connect Firebase to post in this demo group.','warning');}});subscribeAuth((u,p)=>{if(!requireAuth())return;load()});

export async function getMembershipState(groupId){
 const [member,request]=await Promise.all([isGroupMember(groupId),hasGroupRequest(groupId)]);
 return member?"member":request?"pending":"none";
}
