import './theme.js';import {db} from './firebase.js';
import {getFunctions,httpsCallable} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-functions.js';import {subscribeAuth,requireAuth,currentUser} from './auth.js';import {collection,getDocs,query,orderBy,limit,doc,writeBatch,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';import { $, $$, escapeHtml, formatDate, toast, showModal } from './utils.js';import {supportIssue} from './services.js';
let all=[];
function issueCard(i){return `<article class="card issue-card" data-issue data-status="${escapeHtml(i.status)}" data-category="${escapeHtml(i.category)}"><div class="issue-status"><span class="badge primary"><i data-lucide="shield-check"></i> Anonymous Student</span><span class="badge ${i.status==='Resolved'?'success':i.status==='In Progress'?'warning':'primary'}">${escapeHtml(i.status)}</span></div><h3>${escapeHtml(i.title)}</h3><p class="muted">${escapeHtml(i.description)}</p><div class="toolbar small"><span class="badge">${escapeHtml(i.category)}</span><span class="badge">${escapeHtml(i.severity)} severity</span><span class="muted"><i data-lucide="map-pin" class="icon"></i>${escapeHtml(i.location||'Campus')}</span></div><div class="split" style="margin-top:12px"><span class="small muted"><span data-support-count>${i.supportCount||0}</span> students support this · ${formatDate(i.createdAt)}</span><button class="btn sm" data-support="${escapeHtml(i.id)}"><i data-lucide="thumbs-up"></i>Support</button></div></article>`}
async function load(){all=[];if(!db){render(all,'not-connected');return}try{const snap=await getDocs(query(collection(db,'issues'),orderBy('createdAt','desc'),limit(50)));all=snap.docs.map(d=>({id:d.id,...d.data()}))}catch(e){toast('Could not load issues.','error')}render(all)}
function render(items,mode){const box=$('[data-issues]');
 if(mode==='not-connected'){box.innerHTML='<div class="card empty"><i data-lucide="wifi-off"></i><h3>Not connected</h3><p>Connect Firebase to see real campus issues.</p></div>';window.lucide?.createIcons();return}
 box.innerHTML=items.length?items.map(issueCard).join(''):`<div class="card empty"><i data-lucide="circle-alert"></i><h3>No issues found</h3><p>Try a different filter or raise the first issue.</p></div>`;window.lucide?.createIcons()}
function apply(){const status=$('.issue-filter.active')?.dataset.status||'All',category=$('#issueCategory')?.value||'All',term=($('#issueSearch')?.value||'').toLowerCase().trim();render(all.filter(i=>(status==='All'||i.status===status)&&(category==='All'||i.category===category)&&(!term||(i.title||'').toLowerCase().includes(term)||(i.description||'').toLowerCase().includes(term))))}
async function raise(){showModal('Raise an anonymous issue','<form class="form" id="issueForm"><div class="notice"><strong>Your public identity stays private.</strong><div class="small muted">Your profile name, photo, email and UID are never displayed on the public issue feed.</div></div><div class="field"><label>Title</label><input name="title" maxlength="140" required placeholder="What needs attention?"></div><div class="field"><label>Description</label><textarea name="description" maxlength="2500" required placeholder="Explain what is happening and how it affects students..."></textarea></div><div class="grid grid-2"><div class="field"><label>Category</label><select name="category"><option>Classroom</option><option>Faculty</option><option>Hostel</option><option>Library</option><option>Wi-Fi</option><option>Infrastructure</option><option>Transport</option><option>Safety</option><option>Canteen</option><option>Academic</option><option>Other</option></select></div><div class="field"><label>Severity</label><select name="severity"><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></div></div><div class="field"><label>Location</label><input name="location" maxlength="120" placeholder="Block, floor or campus area"></div><label class="check-row"><input type="checkbox" required><span>I understand this issue will be visible to the campus community.</span></label><div style="text-align:right"><button class="btn primary"><i data-lucide="shield-plus"></i>Submit anonymously</button></div></form>');window.lucide?.createIcons();$('#issueForm').addEventListener('submit',async e=>{e.preventDefault();if(!db)return toast('Connect Firebase before submitting a real issue.','warning');const fd=new FormData(e.currentTarget);const submit=e.currentTarget.querySelector('button[type="submit"]');submit.disabled=true;submit.innerHTML='<i data-lucide="loader-circle"></i>Submitting…';window.lucide?.createIcons();try{const call=httpsCallable(getFunctions(),'submitAnonymousIssue');const result=await call({title:String(fd.get('title')).trim(),description:String(fd.get('description')).trim(),category:String(fd.get('category')),severity:String(fd.get('severity')),location:String(fd.get('location')||'').trim()});document.querySelector('.modal-backdrop')?.remove();toast(`Issue submitted. Reference ${result.data.id.slice(-8).toUpperCase()}`);load()}catch(err){submit.disabled=false;submit.innerHTML='<i data-lucide="shield-plus"></i>Submit anonymously';window.lucide?.createIcons();toast(err.message||'Issue could not be submitted.','error')}})}
document.addEventListener('input',e=>{if(e.target.matches('#issueSearch'))apply()});document.addEventListener('change',e=>{if(e.target.matches('#issueCategory'))apply()});document.addEventListener('click',async e=>{if(e.target.closest('[data-raise-issue]'))return raise();const filter=e.target.closest('.issue-filter');if(filter){$$('.issue-filter').forEach(x=>x.classList.remove('active'));filter.classList.add('active');apply()}const btn=e.target.closest('[data-support]');if(btn){const id=btn.dataset.support;if(!db||id.startsWith('demo'))return toast('Demo issue: connect Firebase to save support.','warning');try{const active=await supportIssue(id,currentUser.uid),countEl=btn.closest('.issue-card').querySelector('[data-support-count]');countEl.textContent=String(Math.max(0,Number(countEl.textContent||0)+(active?1:-1)));btn.classList.toggle('active',active);toast(active?'Your support was recorded.':'Support removed.')}catch(err){toast(err.message||'Support could not be recorded.','error')}}});subscribeAuth((u,p)=>{if(!requireAuth())return;load()});

