import {watchMyNotifications} from "./realtime.js";
import './theme.js';import {db} from './firebase.js';import {subscribeAuth,requireAuth,currentUser} from './auth.js';import {getNotifications,markNotificationRead} from './services.js';import { $, escapeHtml,timeAgo,toast } from './utils.js';
function icon(type){return {like:'heart',comment:'message-circle',group:'users-round',event:'calendar-days',issue:'circle-alert',system:'bell'}[type]||'bell'}
async function load(){let items=[];if(db){try{items=await getNotifications(currentUser.uid)}catch(e){toast('Could not load notifications.','error')}}if(!items.length)items=[{id:'demo-n1',type:'system',text:'Welcome to Campus Connect. Your community starts here.',createdAt:new Date(),read:false},{id:'demo-n2',type:'event',text:'Campus Hacknight is coming up on September 18.',createdAt:new Date(Date.now()-3600000),read:true}];$('#notificationList').innerHTML=items.map(n=>`<button class="notification-item ${n.read?'read':''}" data-notification="${escapeHtml(n.id)}"><span class="notif-icon"><i data-lucide="${icon(n.type)}"></i></span><span class="notification-copy"><strong>${escapeHtml(n.title||'Campus Connect')}</strong><span>${escapeHtml(n.text||'')}</span><small>${timeAgo(n.createdAt)}</small></span>${n.read?'':'<span class="unread-dot"></span>'}</button>`).join('');window.lucide?.createIcons()}
document.addEventListener('click',async e=>{const n=e.target.closest('[data-notification]');if(!n||n.dataset.notification.startsWith('demo'))return;try{await markNotificationRead(currentUser.uid,n.dataset.notification);n.classList.add('read')}catch(err){toast(err.message,'error')}});subscribeAuth((u,p)=>{if(!requireAuth())return;load()});

export function startLiveNotifications(render){
 return watchMyNotifications(items=>render(items));
}
