import {getSavedPosts,getMyGroups,getMyEventInterest} from "./data-layer.js";
import './theme.js';import {db,storage} from './firebase.js';import {subscribeAuth,requireAuth,currentProfile,currentUser} from './auth.js';import {doc,updateDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';import { $, escapeHtml, initials, toast, showModal } from './utils.js';import {uploadImage} from './services.js';
let profile;
function render(p){profile=p;$('[data-profile-name]').textContent=p.displayName||'Student';$('[data-profile-bio]').textContent=p.bio||'Part of the Campus Connect community.';$('[data-profile-avatar]').innerHTML=p.photoURL?`<img src="${escapeHtml(p.photoURL)}" alt="Profile photo">`:escapeHtml(initials(p.displayName));$('[data-profile-academic]').textContent=[p.course,p.branch,p.year].filter(Boolean).join(' • ')||'Student';$('#profileCollege').textContent=p.college||'';const sectionEl=$('#profileSection'); if(sectionEl) sectionEl.textContent=p.section?`Section ${p.section}`:'';}
function edit(){showModal('Edit profile','<form class="form" id="profileForm"><div class="field"><label>Name</label><input name="displayName" value="'+escapeHtml(profile.displayName||'')+'" required></div><div class="field"><label>Bio</label><textarea name="bio" maxlength="250">'+escapeHtml(profile.bio||'')+'</textarea></div><div class="field"><label>Profile photo</label><input id="profilePhoto" type="file" accept="image/*"><div id="profileUploadStatus" class="small muted">Use a clear square image under 8 MB.</div></div><div class="grid grid-2"><div class="field"><label>Course</label><input name="course" value="'+escapeHtml(profile.course||'')+'"></div><div class="field"><label>Branch</label><input name="branch" value="'+escapeHtml(profile.branch||'')+'"></div><div class="field"><label>Year</label><input name="year" value="'+escapeHtml(profile.year||'')+'"></div><div class="field"><label>Section</label><input name="section" value="'+escapeHtml(profile.section||'')+'"></div></div><div style="text-align:right"><button class="btn primary">Save changes</button></div></form>');$('#profileForm').addEventListener('submit',async e=>{e.preventDefault();if(!db)return toast('Connect Firebase to save profile changes.','warning');const fd=new FormData(e.currentTarget);try{let photoURL=profile.photoURL||'';const file=$('#profilePhoto').files[0];if(file)photoURL=await uploadImage(file,`users/${currentUser.uid}/avatar-${Date.now()}`,p=>$('#profileUploadStatus').textContent=`Uploading… ${p}%`);const values={displayName:String(fd.get('displayName')).trim(),bio:String(fd.get('bio')||'').trim(),course:String(fd.get('course')||'').trim(),branch:String(fd.get('branch')||'').trim(),year:String(fd.get('year')||'').trim(),section:String(fd.get('section')||'').trim(),photoURL,updatedAt:serverTimestamp()};await updateDoc(doc(db,'users',profile.uid),values);Object.assign(profile,values);render(profile);document.querySelector('.modal-backdrop')?.remove();toast('Profile updated')}catch(err){toast(err.message,'error')}})}
document.addEventListener('click',e=>{if(e.target.closest('[data-edit-profile]'))edit()});subscribeAuth((u,p)=>{if(!requireAuth())return;render(p)});

async function hydrateProfileCollections(){
 const saved=document.querySelector("#savedPostsList,[data-saved-posts]");
 const groups=document.querySelector("#myGroupsList,[data-my-groups]");
 const events=document.querySelector("#myEventsList,[data-my-events]");
 try{
  const [sp,gs,es]=await Promise.all([getSavedPosts(),getMyGroups(),getMyEventInterest()]);
  if(saved) saved.innerHTML=sp.length?sp.map(p=>`<article class="card"><strong>${escapeHtml?.(p.title||p.text||"Saved post")||"Saved post"}</strong><p>${escapeHtml?.(p.text||"")||""}</p></article>`).join(""):'<p class="muted">No saved posts yet.</p>';
  if(groups) groups.innerHTML=gs.length?gs.map(g=>`<a class="card" href="group.html?id=${g.id}"><strong>${g.name||"Group"}</strong><span class="muted">${g.category||""}</span></a>`).join(""):'<p class="muted">You have not joined any groups yet.</p>';
  if(events) events.innerHTML=es.length?es.map(e=>`<a class="card" href="events.html"><strong>${e.title||"Event"}</strong><span class="muted">${e.venue||""}</span></a>`).join(""):'<p class="muted">No interested events.</p>';
 }catch(e){console.warn("Profile collections",e);}
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",hydrateProfileCollections);else hydrateProfileCollections();
